### ISSUE TITLE
Error to install the package

### ISSUE THREAD

**Issue by FVFaleiro** [OscarGOGO/Makurhini#16]
Could you help me install the package? Below is the code, sessionInfo and the error.

```
library(devtools)
find_rtools()
install_github("connectscape/Makurhini", dependencies = TRUE, upgrade = "never")
```

Installing package into ‘C:/Users/BIOTA/AppData/Local/R/win-library/4.3’
(as ‘lib’ is unspecified)
* installing *source* package 'Makurhini' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
**Error: object 'multiprocess' is not exported by 'namespace:future'
Execution halted
ERROR: lazy loading failed for package 'Makurhini'**
* removing 'C:/Users/BIOTA/AppData/Local/R/win-library/4.3/Makurhini'
Warning message:
In i.p(...) :
  installation of package ‘C:/Users/BIOTA/AppData/Local/Temp/RtmpGovxLN/filecd07a916e9f/Makurhini_2.0.6.tar.gz’ had non-zero exit status

`sessionInfo()`
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 11 x64 (build 22621)

Matrix products: default

locale:
[1] LC_COLLATE=Portuguese_Brazil.utf8  LC_CTYPE=Portuguese_Brazil.utf8   
[3] LC_MONETARY=Portuguese_Brazil.utf8 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.utf8    

time zone: America/Sao_Paulo
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.3.1    tools_4.3.1       rstudioapi_0.15.0

**Comment by OscarGOGO** [comment]
Hi, 

Thank you for using Makurhini. We have updated the repository and now the package installation should work

Some tips: 
-   **It is recommended to install the R igraph package (\>= 1.2.6)
    beforehand.**

You can install the released version of Makurhini from
[GitHub](https://github.com) with:

```{r echo=TRUE, eval=FALSE}
library(devtools)
library(remotes)
install_github("connectscape/Makurhini", dependencies = TRUE, upgrade = "never")
```

In case it does not appear in the list of packages, close the R session
and reopen.

- **If the following error occurs during installation**: 
```{r eval=FALSE}
Using github PAT
from envvar GITHUB_PAT Error: Failed to install 'unknown package' from
GitHub: HTTP error 401. Bad credentials
```


Then you can try the following: 

```{r eval=FALSE}
Sys.getenv("GITHUB_PAT")
Sys.unsetenv("GITHUB_PAT")
```


Best wishes

**Comment by FVFaleiro** [comment]
Thanks! It works! :)
