### ISSUE TITLE
[Feature request] Adding the functionability of computing and returning corridor networks with width

### ISSUE THREAD

**Issue by CWen001** [OscarGOGO/Makurhini#9]
Hello. `Makurhini` has provided excellent infrastructure to analyze fragmentation and connectivity. I'm wondering if it is possible to add the functionality of computing and returning corridor networks with width.

In conservation planning and related fields, plotting and analyzing corridor networks with width from multiple ecological sources are getting more and more attention. However, users often have to leave R world for Linkage Mapper in ArcGIS to finish the job (https://linkagemapper.org/). Although there are some other tools to draw and analyze corridor networks in R, for example, `grainscape`, they cannot represent the width of the corridors.

It seems that the feature is within the scope of `Makurhini`, and the package already has much infrastructure to analyze corridors. Is it possible to take one step further for this functionality? I understand very much this is an open-source project, and the developer's time is invaluable. Please feel free to close if it is out of plan. Thank you very much.

**Comment by OscarGOGO** [comment]
Hello. Nice to read you and an apology for the delay in answering, I had some personal problems but I'm back. 

This is an excellent proposal and is being considered.  You are absolutely right, one constraint is scheduling time, we hope to take advantage of the needs of future research projects related to connectivity. We hope in the coming months to implement a couple of packages, the first one aimed at identifying patches in the landscape using habitat models and to build resilience matrices. The second package would be for modeling least-cost paths and least-cost corridors. We will keep you informed of upcoming releases. 

Cheers,
